export default [
  {
    id: 1,
    city: "Halifax",
    state: "Nova Scotia",
    country: "Canada",
    remote: false,
  },
  {
    id: 2,
    city: "Montreal",
    state: "Quebec",
    country: "Canada",
    remote: false,
  },
  {
    id: 3,
    city: "Ottawa",
    state: "Ontario",
    country: "Canada",
    remote: false,
  },
  {
    id: 4,
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    remote: false,
  },
  {
    id: 5,
    city: "Calgary",
    state: "Alberta",
    country: "Canada",
    remote: false,
  },
  {
    id: 6,
    city: "Vancouver",
    state: "British Columbia",
    country: "Canada",
    remote: false,
  },
  {
    id: 7,
    city: "New York",
    state: "New York",
    country: "United States",
    remote: false,
  },
  {
    id: 8,
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    remote: false,
  },
  {
    id: 9,
    city: "Washington",
    state: "District of Columbia",
    country: "United States",
    remote: false,
  },
  {
    id: 10,
    city: "Austin",
    state: "Texas",
    country: "United States",
    remote: false,
  },
  {
    id: 11,
    city: "Atlanta",
    state: "Georgia",
    country: "United States",
    remote: false,
  },
  {
    id: 12,
    city: "Miami",
    state: "Florida",
    country: "United States",
    remote: false,
  },
  {
    id: 13,
    city: "Denver",
    state: "Colorado",
    country: "United States",
    remote: false,
  },
  {
    id: 14,
    city: "Phoenix",
    state: "Arizona",
    country: "United States",
    remote: false,
  },
  {
    id: 15,
    city: "Seattle",
    state: "Washington",
    country: "United States",
    remote: false,
  },
  {
    id: 16,
    city: "San Francisco",
    state: "California",
    country: "United States",
    remote: false,
  },
  {
    id: 17,
    remote: true,
  },
  {
    id: 18,
    remote: true,
  },
  {
    id: 19,
    remote: true,
  },
  {
    id: 20,
    remote: true,
  },
];
