export default [
  {
    id: 1,
    name: "Halifax",
    city: "Halifax",
    state: "Nova Scotia",
    country: "Canada",
    remote: false,
  },
  {
    id: 2,
    name: "Montreal",
    city: "Montreal",
    state: "Quebec",
    country: "Canada",
    remote: false,
  },
  {
    id: 3,
    name: "Ottawa",
    city: "Ottawa",
    state: "Ontario",
    country: "Canada",
    remote: false,
  },
  {
    id: 4,
    name: "Toronto",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    remote: false,
  },
  {
    id: 5,
    name: "Calgary",
    city: "Calgary",
    state: "Alberta",
    country: "Canada",
    remote: false,
  },
  {
    id: 6,
    name: "Vancouver",
    city: "Vancouver",
    state: "British Columbia",
    country: "Canada",
    remote: false,
  },
  {
    id: 7,
    name: "New York",
    city: "New York",
    state: "New York",
    country: "United States",
    remote: false,
  },
  {
    id: 8,
    name: "Chicago",
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    remote: false,
  },
  {
    id: 9,
    name: "Washington",
    city: "Washington",
    state: "District of Columbia",
    country: "United States",
    remote: false,
  },
  {
    id: 10,
    name: "Austin",
    city: "Austin",
    state: "Texas",
    country: "United States",
    remote: false,
  },
  {
    id: 11,
    name: "Atlanta",
    city: "Atlanta",
    state: "Georgia",
    country: "United States",
    remote: false,
  },
  {
    id: 12,
    name: "Miami",
    city: "Miami",
    state: "Florida",
    country: "United States",
    remote: false,
  },
  {
    id: 13,
    name: "Denver",
    city: "Denver",
    state: "Colorado",
    country: "United States",
    remote: false,
  },
  {
    id: 14,
    name: "Phoenix",
    city: "Phoenix",
    state: "Arizona",
    country: "United States",
    remote: false,
  },
  {
    id: 15,
    name: "Seattle",
    city: "Seattle",
    state: "Washington",
    country: "United States",
    remote: false,
  },
  {
    id: 16,
    name: "San Francisco",
    city: "San Francisco",
    state: "California",
    country: "United States",
    remote: false,
  },
  {
    id: 17,
    name: "Mondays Remote",
    remote: true,
  },
  {
    id: 18,
    name: "Tuesdays Remote",
    remote: true,
  },
  {
    id: 19,
    name: "Wednesdays Remote",
    remote: true,
  },
  {
    id: 20,
    name: "Thursdays Remote",
    remote: true,
  },
];
