export default [
  {
    id: 1,
    name: "Halifax",
    city: "Halifax",
    region_id: 6,
    country_id: 1,
    remote: false,
  },
  {
    id: 2,
    name: "Montreal",
    city: "Montreal",
    region_id: 9,
    country_id: 1,
    remote: false,
  },
  {
    id: 3,
    name: "Ottawa",
    city: "Ottawa",
    region_id: 7,
    country_id: 1,
    remote: false,
  },
  {
    id: 4,
    name: "Toronto",
    city: "Toronto",
    region_id: 7,
    country_id: 1,
    remote: false,
  },
  {
    id: 5,
    name: "Calgary",
    city: "Calgary",
    region_id: 1,
    country_id: 1,
    remote: false,
  },
  {
    id: 6,
    name: "Vancouver",
    city: "Vancouver",
    region_id: 2,
    country_id: 1,
    remote: false,
  },
  {
    id: 7,
    name: "New York",
    city: "New York",
    region_id: 45,
    country_id: 2,
    remote: false,
  },
  {
    id: 8,
    name: "Chicago",
    city: "Chicago",
    region_id: 26,
    country_id: 2,
    remote: false,
  },
  {
    id: 9,
    name: "Washington",
    city: "Washington",
    region_id: 64,
    country_id: 2,
    remote: false,
  },
  {
    id: 10,
    name: "Austin",
    city: "Austin",
    region_id: 56,
    country_id: 2,
    remote: false,
  },
  {
    id: 11,
    name: "Atlanta",
    city: "Atlanta",
    region_id: 23,
    country_id: 2,
    remote: false,
  },
  {
    id: 12,
    name: "Miami",
    city: "Miami",
    region_id: 22,
    country_id: 2,
    remote: false,
  },
  {
    id: 13,
    name: "Denver",
    city: "Denver",
    region_id: 19,
    country_id: 2,
    remote: false,
  },
  {
    id: 14,
    name: "Phoenix",
    city: "Phoenix",
    region_id: 16,
    country_id: 2,
    remote: false,
  },
  {
    id: 15,
    name: "Seattle",
    city: "Seattle",
    region_id: 60,
    country_id: 2,
    remote: false,
  },
  {
    id: 16,
    name: "San Francisco",
    city: "San Francisco",
    region_id: 18,
    country_id: 2,
    remote: false,
  },
  {
    id: 17,
    name: "Mondays Remote",
    remote: true,
  },
  {
    id: 18,
    name: "Tuesdays Remote",
    remote: true,
  },
  {
    id: 19,
    name: "Wednesdays Remote",
    remote: true,
  },
  {
    id: 20,
    name: "Thursdays Remote",
    remote: true,
  },
];
